name: Sync Front with Master

on:
  push:
    branches:
      - master

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge master into front
        run: |
          git fetch origin
          git checkout front
          git merge origin/master --no-edit
          git push origin front
